// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: orion/v1/agent.proto

package orionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU in thousandths of a core.
	CpuMillis     int64 `protobuf:"varint,1,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	MemoryBytes   int64 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_orion_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Resources) GetCpuMillis() int64 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *Resources) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	KernelVersion string                 `protobuf:"bytes,5,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_orion_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RuntimeInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RuntimeInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RuntimeInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

type RegisterRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeName string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// address is host:port where this agent serves its local API (logs).
	Address  string            `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Labels   map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capacity *Resources        `protobuf:"bytes,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// allocatable is capacity minus the reservation the agent keeps for itself
	// and the operating system.
	Allocatable *Resources   `protobuf:"bytes,5,opt,name=allocatable,proto3" json:"allocatable,omitempty"`
	Runtime     *RuntimeInfo `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// agent_started_at lets the control plane distinguish an agent restart from
	// a continuing session.
	AgentStartedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=agent_started_at,json=agentStartedAt,proto3" json:"agent_started_at,omitempty"`
	AgentVersion   string                 `protobuf:"bytes,8,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_orion_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetCapacity() *Resources {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *RegisterRequest) GetAllocatable() *Resources {
	if x != nil {
		return x.Allocatable
	}
	return nil
}

func (x *RegisterRequest) GetRuntime() *RuntimeInfo {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *RegisterRequest) GetAgentStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AgentStartedAt
	}
	return nil
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type RegisterResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	NodeUid string                 `protobuf:"bytes,1,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"`
	// heartbeat_interval and self_fence_timeout are assigned by the control
	// plane so that the failure-detection window and the agent's self-fencing
	// deadline are configured in one place and cannot drift apart.
	HeartbeatIntervalMs int64 `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	// self_fence_timeout_ms is how long the agent may run without reaching the
	// control plane before it must stop its own workloads. It is always shorter
	// than the control plane's eviction deadline, which is what prevents a
	// partitioned node from running containers the cluster has already replaced.
	SelfFenceTimeoutMs int64  `protobuf:"varint,3,opt,name=self_fence_timeout_ms,json=selfFenceTimeoutMs,proto3" json:"self_fence_timeout_ms,omitempty"`
	ClusterId          string `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_orion_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *RegisterResponse) GetSelfFenceTimeoutMs() int64 {
	if x != nil {
		return x.SelfFenceTimeoutMs
	}
	return 0
}

func (x *RegisterResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type WorkloadStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid   string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// phase is an Orion WorkloadPhase name: Starting, Running, Failed, ...
	Phase string `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	// health is Healthy, Unhealthy or Unknown.
	Health       string `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	ContainerId  string `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Reason       string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Message      string `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	RestartCount int32  `protobuf:"varint,8,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	// exit_code is only meaningful once the container has stopped; has_exit_code
	// distinguishes "exited with 0" from "has not exited".
	ExitCode    int32                  `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	HasExitCode bool                   `protobuf:"varint,10,opt,name=has_exit_code,json=hasExitCode,proto3" json:"has_exit_code,omitempty"`
	StartedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Usage       *Resources             `protobuf:"bytes,13,opt,name=usage,proto3" json:"usage,omitempty"`
	// host_ports maps container port -> published host port.
	HostPorts     map[int32]int32 `protobuf:"bytes,14,rep,name=host_ports,json=hostPorts,proto3" json:"host_ports,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_orion_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *WorkloadStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadStatus) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *WorkloadStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *WorkloadStatus) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *WorkloadStatus) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *WorkloadStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *WorkloadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkloadStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *WorkloadStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WorkloadStatus) GetHasExitCode() bool {
	if x != nil {
		return x.HasExitCode
	}
	return false
}

func (x *WorkloadStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *WorkloadStatus) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *WorkloadStatus) GetUsage() *Resources {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *WorkloadStatus) GetHostPorts() map[int32]int32 {
	if x != nil {
		return x.HostPorts
	}
	return nil
}

type NodeCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCondition) Reset() {
	*x = NodeCondition{}
	mi := &file_orion_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCondition) ProtoMessage() {}

func (x *NodeCondition) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCondition.ProtoReflect.Descriptor instead.
func (*NodeCondition) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *NodeCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeCondition) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *NodeCondition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NodeCondition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SyncRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NodeName    string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeUid     string                 `protobuf:"bytes,2,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"`
	Capacity    *Resources             `protobuf:"bytes,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Allocatable *Resources             `protobuf:"bytes,4,opt,name=allocatable,proto3" json:"allocatable,omitempty"`
	// usage is measured consumption across all containers on this node.
	Usage      *Resources       `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	Runtime    *RuntimeInfo     `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Conditions []*NodeCondition `protobuf:"bytes,7,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// workloads is every workload this agent currently observes, including ones
	// it has finished tearing down. The control plane treats it as complete.
	Workloads     []*WorkloadStatus `protobuf:"bytes,8,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_orion_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SyncRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *SyncRequest) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *SyncRequest) GetCapacity() *Resources {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *SyncRequest) GetAllocatable() *Resources {
	if x != nil {
		return x.Allocatable
	}
	return nil
}

func (x *SyncRequest) GetUsage() *Resources {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *SyncRequest) GetRuntime() *RuntimeInfo {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *SyncRequest) GetConditions() []*NodeCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *SyncRequest) GetWorkloads() []*WorkloadStatus {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Container     int32                  `protobuf:"varint,2,opt,name=container,proto3" json:"container,omitempty"`
	Host          int32                  `protobuf:"varint,3,opt,name=host,proto3" json:"host,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_orion_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Port) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Port) GetContainer() int32 {
	if x != nil {
		return x.Container
	}
	return 0
}

func (x *Port) GetHost() int32 {
	if x != nil {
		return x.Host
	}
	return 0
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_orion_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HealthCheck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // http | tcp | process
	Path             string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Port             int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	InitialDelayMs   int64                  `protobuf:"varint,4,opt,name=initial_delay_ms,json=initialDelayMs,proto3" json:"initial_delay_ms,omitempty"`
	IntervalMs       int64                  `protobuf:"varint,5,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	TimeoutMs        int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	FailureThreshold int32                  `protobuf:"varint,7,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	SuccessThreshold int32                  `protobuf:"varint,8,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_orion_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheck) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HealthCheck) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HealthCheck) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HealthCheck) GetInitialDelayMs() int64 {
	if x != nil {
		return x.InitialDelayMs
	}
	return 0
}

func (x *HealthCheck) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *HealthCheck) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *HealthCheck) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *HealthCheck) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

// AssignedWorkload is the complete specification the agent needs to run one
// container. It is self-contained on purpose: the agent never has to look
// anything else up, so it can keep working through a control-plane outage.
type AssignedWorkload struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Name                     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid                      string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Image                    string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Command                  []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Args                     []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	Env                      []*EnvVar              `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty"`
	Ports                    []*Port                `protobuf:"bytes,7,rep,name=ports,proto3" json:"ports,omitempty"`
	Request                  *Resources             `protobuf:"bytes,8,opt,name=request,proto3" json:"request,omitempty"`
	Limit                    *Resources             `protobuf:"bytes,9,opt,name=limit,proto3" json:"limit,omitempty"`
	RestartPolicy            string                 `protobuf:"bytes,10,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	TerminationGracePeriodMs int64                  `protobuf:"varint,11,opt,name=termination_grace_period_ms,json=terminationGracePeriodMs,proto3" json:"termination_grace_period_ms,omitempty"`
	HealthCheck              *HealthCheck           `protobuf:"bytes,12,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	// desired_state is Running or Terminated. Terminated means the agent should
	// stop and remove the container; the workload record stays until the agent
	// confirms it is gone.
	DesiredState  string            `protobuf:"bytes,13,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	Labels        map[string]string `protobuf:"bytes,14,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedWorkload) Reset() {
	*x = AssignedWorkload{}
	mi := &file_orion_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedWorkload) ProtoMessage() {}

func (x *AssignedWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedWorkload.ProtoReflect.Descriptor instead.
func (*AssignedWorkload) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *AssignedWorkload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssignedWorkload) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AssignedWorkload) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AssignedWorkload) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *AssignedWorkload) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AssignedWorkload) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *AssignedWorkload) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *AssignedWorkload) GetRequest() *Resources {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AssignedWorkload) GetLimit() *Resources {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *AssignedWorkload) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

func (x *AssignedWorkload) GetTerminationGracePeriodMs() int64 {
	if x != nil {
		return x.TerminationGracePeriodMs
	}
	return 0
}

func (x *AssignedWorkload) GetHealthCheck() *HealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *AssignedWorkload) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *AssignedWorkload) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// workloads is the complete set this node should be running. Anything the
	// agent has that is absent from this list is no longer wanted and must be
	// removed — which is how an orphaned container left by a crashed agent gets
	// cleaned up.
	Workloads []*AssignedWorkload `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	// accepted is false when the control plane does not recognize this node,
	// for example after its record was deleted. The agent must re-register.
	Accepted            bool   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason        string `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	HeartbeatIntervalMs int64  `protobuf:"varint,4,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	SelfFenceTimeoutMs  int64  `protobuf:"varint,5,opt,name=self_fence_timeout_ms,json=selfFenceTimeoutMs,proto3" json:"self_fence_timeout_ms,omitempty"`
	// leader_address is set when this replica is not the leader, so the agent
	// can reconnect without waiting for a DNS or load-balancer update.
	LeaderAddress string `protobuf:"bytes,6,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_orion_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *SyncResponse) GetWorkloads() []*AssignedWorkload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

func (x *SyncResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SyncResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *SyncResponse) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *SyncResponse) GetSelfFenceTimeoutMs() int64 {
	if x != nil {
		return x.SelfFenceTimeoutMs
	}
	return 0
}

func (x *SyncResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeUid       string                 `protobuf:"bytes,2,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_orion_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DeregisterRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *DeregisterRequest) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *DeregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_orion_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_orion_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *DeregisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_orion_v1_agent_proto protoreflect.FileDescriptor

const file_orion_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14orion/v1/agent.proto\x12\borion.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n" +
	"\tResources\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x01 \x01(\x03R\tcpuMillis\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\"\x86\x01\n" +
	"\vRuntimeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12%\n" +
	"\x0ekernel_version\x18\x05 \x01(\tR\rkernelVersion\"\xc6\x03\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12=\n" +
	"\x06labels\x18\x03 \x03(\v2%.orion.v1.RegisterRequest.LabelsEntryR\x06labels\x12/\n" +
	"\bcapacity\x18\x04 \x01(\v2\x13.orion.v1.ResourcesR\bcapacity\x125\n" +
	"\vallocatable\x18\x05 \x01(\v2\x13.orion.v1.ResourcesR\vallocatable\x12/\n" +
	"\aruntime\x18\x06 \x01(\v2\x15.orion.v1.RuntimeInfoR\aruntime\x12D\n" +
	"\x10agent_started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0eagentStartedAt\x12#\n" +
	"\ragent_version\x18\b \x01(\tR\fagentVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bnode_uid\x18\x01 \x01(\tR\anodeUid\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x03R\x13heartbeatIntervalMs\x121\n" +
	"\x15self_fence_timeout_ms\x18\x03 \x01(\x03R\x12selfFenceTimeoutMs\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\"\xc8\x04\n" +
	"\x0eWorkloadStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x16\n" +
	"\x06health\x18\x04 \x01(\tR\x06health\x12!\n" +
	"\fcontainer_id\x18\x05 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12#\n" +
	"\rrestart_count\x18\b \x01(\x05R\frestartCount\x12\x1b\n" +
	"\texit_code\x18\t \x01(\x05R\bexitCode\x12\"\n" +
	"\rhas_exit_code\x18\n" +
	" \x01(\bR\vhasExitCode\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12)\n" +
	"\x05usage\x18\r \x01(\v2\x13.orion.v1.ResourcesR\x05usage\x12F\n" +
	"\n" +
	"host_ports\x18\x0e \x03(\v2'.orion.v1.WorkloadStatus.HostPortsEntryR\thostPorts\x1a<\n" +
	"\x0eHostPortsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"m\n" +
	"\rNodeCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xfa\x02\n" +
	"\vSyncRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x19\n" +
	"\bnode_uid\x18\x02 \x01(\tR\anodeUid\x12/\n" +
	"\bcapacity\x18\x03 \x01(\v2\x13.orion.v1.ResourcesR\bcapacity\x125\n" +
	"\vallocatable\x18\x04 \x01(\v2\x13.orion.v1.ResourcesR\vallocatable\x12)\n" +
	"\x05usage\x18\x05 \x01(\v2\x13.orion.v1.ResourcesR\x05usage\x12/\n" +
	"\aruntime\x18\x06 \x01(\v2\x15.orion.v1.RuntimeInfoR\aruntime\x127\n" +
	"\n" +
	"conditions\x18\a \x03(\v2\x17.orion.v1.NodeConditionR\n" +
	"conditions\x126\n" +
	"\tworkloads\x18\b \x03(\v2\x18.orion.v1.WorkloadStatusR\tworkloads\"h\n" +
	"\x04Port\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\x05R\tcontainer\x12\x12\n" +
	"\x04host\x18\x03 \x01(\x05R\x04host\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"2\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x8d\x02\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12(\n" +
	"\x10initial_delay_ms\x18\x04 \x01(\x03R\x0einitialDelayMs\x12\x1f\n" +
	"\vinterval_ms\x18\x05 \x01(\x03R\n" +
	"intervalMs\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\x12+\n" +
	"\x11failure_threshold\x18\a \x01(\x05R\x10failureThreshold\x12+\n" +
	"\x11success_threshold\x18\b \x01(\x05R\x10successThreshold\"\xe0\x04\n" +
	"\x10AssignedWorkload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12\"\n" +
	"\x03env\x18\x06 \x03(\v2\x10.orion.v1.EnvVarR\x03env\x12$\n" +
	"\x05ports\x18\a \x03(\v2\x0e.orion.v1.PortR\x05ports\x12-\n" +
	"\arequest\x18\b \x01(\v2\x13.orion.v1.ResourcesR\arequest\x12)\n" +
	"\x05limit\x18\t \x01(\v2\x13.orion.v1.ResourcesR\x05limit\x12%\n" +
	"\x0erestart_policy\x18\n" +
	" \x01(\tR\rrestartPolicy\x12=\n" +
	"\x1btermination_grace_period_ms\x18\v \x01(\x03R\x18terminationGracePeriodMs\x128\n" +
	"\fhealth_check\x18\f \x01(\v2\x15.orion.v1.HealthCheckR\vhealthCheck\x12#\n" +
	"\rdesired_state\x18\r \x01(\tR\fdesiredState\x12>\n" +
	"\x06labels\x18\x0e \x03(\v2&.orion.v1.AssignedWorkload.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x02\n" +
	"\fSyncResponse\x128\n" +
	"\tworkloads\x18\x01 \x03(\v2\x1a.orion.v1.AssignedWorkloadR\tworkloads\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\x122\n" +
	"\x15heartbeat_interval_ms\x18\x04 \x01(\x03R\x13heartbeatIntervalMs\x121\n" +
	"\x15self_fence_timeout_ms\x18\x05 \x01(\x03R\x12selfFenceTimeoutMs\x12%\n" +
	"\x0eleader_address\x18\x06 \x01(\tR\rleaderAddress\"c\n" +
	"\x11DeregisterRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x19\n" +
	"\bnode_uid\x18\x02 \x01(\tR\anodeUid\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"0\n" +
	"\x12DeregisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\xd0\x01\n" +
	"\vNodeService\x12A\n" +
	"\bRegister\x12\x19.orion.v1.RegisterRequest\x1a\x1a.orion.v1.RegisterResponse\x125\n" +
	"\x04Sync\x12\x15.orion.v1.SyncRequest\x1a\x16.orion.v1.SyncResponse\x12G\n" +
	"\n" +
	"Deregister\x12\x1b.orion.v1.DeregisterRequest\x1a\x1c.orion.v1.DeregisterResponseB8Z6github.com/sujalbistaa/orion/pkg/proto/orionv1;orionv1b\x06proto3"

var (
	file_orion_v1_agent_proto_rawDescOnce sync.Once
	file_orion_v1_agent_proto_rawDescData []byte
)

func file_orion_v1_agent_proto_rawDescGZIP() []byte {
	file_orion_v1_agent_proto_rawDescOnce.Do(func() {
		file_orion_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orion_v1_agent_proto_rawDesc), len(file_orion_v1_agent_proto_rawDesc)))
	})
	return file_orion_v1_agent_proto_rawDescData
}

var file_orion_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_orion_v1_agent_proto_goTypes = []any{
	(*Resources)(nil),             // 0: orion.v1.Resources
	(*RuntimeInfo)(nil),           // 1: orion.v1.RuntimeInfo
	(*RegisterRequest)(nil),       // 2: orion.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 3: orion.v1.RegisterResponse
	(*WorkloadStatus)(nil),        // 4: orion.v1.WorkloadStatus
	(*NodeCondition)(nil),         // 5: orion.v1.NodeCondition
	(*SyncRequest)(nil),           // 6: orion.v1.SyncRequest
	(*Port)(nil),                  // 7: orion.v1.Port
	(*EnvVar)(nil),                // 8: orion.v1.EnvVar
	(*HealthCheck)(nil),           // 9: orion.v1.HealthCheck
	(*AssignedWorkload)(nil),      // 10: orion.v1.AssignedWorkload
	(*SyncResponse)(nil),          // 11: orion.v1.SyncResponse
	(*DeregisterRequest)(nil),     // 12: orion.v1.DeregisterRequest
	(*DeregisterResponse)(nil),    // 13: orion.v1.DeregisterResponse
	nil,                           // 14: orion.v1.RegisterRequest.LabelsEntry
	nil,                           // 15: orion.v1.WorkloadStatus.HostPortsEntry
	nil,                           // 16: orion.v1.AssignedWorkload.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_orion_v1_agent_proto_depIdxs = []int32{
	14, // 0: orion.v1.RegisterRequest.labels:type_name -> orion.v1.RegisterRequest.LabelsEntry
	0,  // 1: orion.v1.RegisterRequest.capacity:type_name -> orion.v1.Resources
	0,  // 2: orion.v1.RegisterRequest.allocatable:type_name -> orion.v1.Resources
	1,  // 3: orion.v1.RegisterRequest.runtime:type_name -> orion.v1.RuntimeInfo
	17, // 4: orion.v1.RegisterRequest.agent_started_at:type_name -> google.protobuf.Timestamp
	17, // 5: orion.v1.WorkloadStatus.started_at:type_name -> google.protobuf.Timestamp
	17, // 6: orion.v1.WorkloadStatus.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 7: orion.v1.WorkloadStatus.usage:type_name -> orion.v1.Resources
	15, // 8: orion.v1.WorkloadStatus.host_ports:type_name -> orion.v1.WorkloadStatus.HostPortsEntry
	0,  // 9: orion.v1.SyncRequest.capacity:type_name -> orion.v1.Resources
	0,  // 10: orion.v1.SyncRequest.allocatable:type_name -> orion.v1.Resources
	0,  // 11: orion.v1.SyncRequest.usage:type_name -> orion.v1.Resources
	1,  // 12: orion.v1.SyncRequest.runtime:type_name -> orion.v1.RuntimeInfo
	5,  // 13: orion.v1.SyncRequest.conditions:type_name -> orion.v1.NodeCondition
	4,  // 14: orion.v1.SyncRequest.workloads:type_name -> orion.v1.WorkloadStatus
	8,  // 15: orion.v1.AssignedWorkload.env:type_name -> orion.v1.EnvVar
	7,  // 16: orion.v1.AssignedWorkload.ports:type_name -> orion.v1.Port
	0,  // 17: orion.v1.AssignedWorkload.request:type_name -> orion.v1.Resources
	0,  // 18: orion.v1.AssignedWorkload.limit:type_name -> orion.v1.Resources
	9,  // 19: orion.v1.AssignedWorkload.health_check:type_name -> orion.v1.HealthCheck
	16, // 20: orion.v1.AssignedWorkload.labels:type_name -> orion.v1.AssignedWorkload.LabelsEntry
	10, // 21: orion.v1.SyncResponse.workloads:type_name -> orion.v1.AssignedWorkload
	2,  // 22: orion.v1.NodeService.Register:input_type -> orion.v1.RegisterRequest
	6,  // 23: orion.v1.NodeService.Sync:input_type -> orion.v1.SyncRequest
	12, // 24: orion.v1.NodeService.Deregister:input_type -> orion.v1.DeregisterRequest
	3,  // 25: orion.v1.NodeService.Register:output_type -> orion.v1.RegisterResponse
	11, // 26: orion.v1.NodeService.Sync:output_type -> orion.v1.SyncResponse
	13, // 27: orion.v1.NodeService.Deregister:output_type -> orion.v1.DeregisterResponse
	25, // [25:28] is the sub-list for method output_type
	22, // [22:25] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_orion_v1_agent_proto_init() }
func file_orion_v1_agent_proto_init() {
	if File_orion_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orion_v1_agent_proto_rawDesc), len(file_orion_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orion_v1_agent_proto_goTypes,
		DependencyIndexes: file_orion_v1_agent_proto_depIdxs,
		MessageInfos:      file_orion_v1_agent_proto_msgTypes,
	}.Build()
	File_orion_v1_agent_proto = out.File
	file_orion_v1_agent_proto_goTypes = nil
	file_orion_v1_agent_proto_depIdxs = nil
}
